name: data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess/owid.ts
      - ./postprocess/jhu-csse.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: 'Create StatsNZ axios config'
        env:
          STATSNZ_API_KEY: ${{ secrets.STATSNZ_API_KEY }}
        run: |
          echo "{ \"headers\": {  \"Ocp-Apim-Subscription-Key\": \"$STATSNZ_API_KEY\" } }" > $RUNNER_TEMP/statsnz_axios_config.json
      - name: Fetch StatsNZ data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.stats.govt.nz/opendata/v1/Covid-19Indicators/Observations?$filter=ResourceID%20eq%20'CPWEE2'%20&$select=Period,Label1,Value&$orderby=Period,Label1
          downloaded_filename: ./data/statsnz/weekly_deaths.json
          postprocess: ./postprocess/statsnz.ts
          axios_config: ${{ format('{0}/{1}', runner.temp, 'statsnz_axios_config.json') }}
      - name: Fetch OWID data
        uses: githubocto/flat@v3
        with:
          http_url: https://covid.ourworldindata.org/data/owid-covid-data.csv
          downloaded_filename: ./data/owid/owid-covid-data.csv
          postprocess: ./postprocess/owid.ts
      - name: Fetch JHU CSSE deaths data
        uses: githubocto/flat@v3
        with:
          http_url: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv
          downloaded_filename: ./data/jhu-csse/time_series_covid19_deaths_global.csv
          postprocess: ./postprocess/jhu-csse.ts
      - name: Fetch JHU CSSE confirmed cases data
        uses: githubocto/flat@v3
        with:
          http_url: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv
          downloaded_filename: ./data/jhu-csse/time_series_covid19_confirmed_global.csv
          postprocess: ./postprocess/jhu-csse.ts
      - name: Fetch MOH vaccine data
        uses: githubocto/flat@v3
        with:
          http_url: https://raw.githubusercontent.com/minhealthnz/nz-covid-data/main/vaccine-data/latest/doses_by_date.csv
          downloaded_filename: ./data/moh/doses_by_date.csv
      - name: Fetch MOH current cases data page
        uses: githubocto/flat@v3
        with:
          http_url: https://www.health.govt.nz/covid-19-novel-coronavirus/covid-19-data-and-statistics/covid-19-current-cases
          downloaded_filename: ./data/moh/covid-19-current-cases/covid-19-current-cases.html
          postprocess: ./postprocess/moh.ts
      - name: Fetch MOH case demographics data page
        uses: githubocto/flat@v3
        with:
          http_url: https://www.health.govt.nz/covid-19-novel-coronavirus/covid-19-data-and-statistics/covid-19-case-demographics
          downloaded_filename: ./data/moh/covid-19-case-demographics/covid-19-case-demographics.html
          postprocess: ./postprocess/moh.ts
      - name: Fetch MOH source of cases data page
        uses: githubocto/flat@v3
        with:
          http_url: https://www.health.govt.nz/covid-19-novel-coronavirus/covid-19-data-and-statistics/covid-19-source-cases
          downloaded_filename: ./data/moh/covid-19-source-cases/covid-19-source-cases.html
          postprocess: ./postprocess/moh.ts
      - name: Fetch MOH testing data page
        uses: githubocto/flat@v3
        with:
          http_url: https://www.health.govt.nz/covid-19-novel-coronavirus/covid-19-data-and-statistics/testing-covid-19
          downloaded_filename: ./data/moh/testing-covid-19/testing-covid-19.html
          postprocess: ./postprocess/moh.ts
      - name: Fetch MOH vaccine data page
        uses: githubocto/flat@v3
        with:
          http_url: https://www.health.govt.nz/covid-19-novel-coronavirus/covid-19-data-and-statistics/covid-19-vaccine-data
          downloaded_filename: ./data/moh/covid-19-vaccine-data/covid-19-vaccine-data.html
          postprocess: ./postprocess/moh.ts
