name: Get JHU CSSE data
on:
  schedule:
    # The commits in CSSEGISandData/COVID-19 repo suggest that these files are updated just before 5am UTC each day.
    - cron: 5 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/jhucsse.yml
      - ./postprocess/jhu-csse.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Fetch JHU CSSE deaths data
        uses: githubocto/flat@v3
        with:
          http_url: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv
          downloaded_filename: ./data/jhu-csse/raw-data/time_series_covid19_deaths_global.csv
          postprocess: ./postprocess/jhu-csse/jhu-csse.ts
      - name: Fetch JHU CSSE confirmed cases data
        uses: githubocto/flat@v3
        with:
          http_url: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv
          downloaded_filename: ./data/jhu-csse/raw-data/time_series_covid19_confirmed_global.csv
          postprocess: ./postprocess/jhu-csse/jhu-csse.ts
  postprocess:
    runs-on: ubuntu-latest
    needs: scheduled
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Tidy and combine data
        run: deno run -A --unstable ./postprocess/jhu-csse/tidy.ts
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
