# https://github.com/stefanzweifel/git-auto-commit-action

# Every 15 mins after 1pm:
#   Job1:
#     - if: not long enough since we wrote the last one (< 24hrs and before the next one)
#       then: output = "SKIP"
#     - if: latest page downloaded is not new
#       then: output = "SKIP"
#     - output = "PROCEED"
#   Job2:
#     - Only run if Job1.OUTPUT="PROCEED"

name: Get MOH data
on:
  schedule:
    # MOH pages are updated at about 1pm each day so schedule at 2pm NZDT = 1am UTC
    - cron: 0 1 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/moh.yml
      - ./postprocess/moh.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Fetch MOH COVID Case Counts data
        uses: githubocto/flat@v3
        with:
          http_url: https://github.com/minhealthnz/nz-covid-data/blob/main/cases/covid-case-counts.csv?raw=true
          downloaded_filename: ./data/moh/covid-case-counts.csv
      - name: Fetch MOH COVID Cases Counts Location data
        uses: githubocto/flat@v3
        with:
          http_url: https://github.com/minhealthnz/nz-covid-data/blob/main/cases/covid-cases-counts-location.xlsx?raw=true
          downloaded_filename: ./data/moh/covid-cases-counts-location.xlsx
      - name: Fetch MOH COVID Cases in Hospital Counts Location data
        uses: githubocto/flat@v3
        with:
          http_url: https://github.com/minhealthnz/nz-covid-data/blob/main/cases/covid-cases-in-hospital-counts-location.xlsx?raw=true
          downloaded_filename: ./data/moh/covid-cases-in-hospital-counts-location.xlsx
      - name: Fetch MOH COVID Weekly Deaths data
        uses: githubocto/flat@v3
        with:
          http_url: https://github.com/minhealthnz/nz-covid-data/blob/main/cases/weekly-deaths.csv?raw=true
          downloaded_filename: ./data/moh/weekly-deaths.csv
      - name: Fetch MOH COVID Weekly Hospitalisations data  
        uses: githubocto/flat@v3
        with:
          http_url: https://github.com/minhealthnz/nz-covid-data/blob/main/cases/weekly-hospitalisations-for-covid.csv?raw=true
          downloaded_filename: ./data/moh/weekly-hospitalisations-for-covid.csv
      
      # Keeping this here to get the link to and download the vaccination data xlsx 
      - name: Fetch MOH vaccine data page
        uses: githubocto/flat@v3
        with:
          http_url: https://www.health.govt.nz/covid-19-novel-coronavirus/covid-19-data-and-statistics/covid-19-vaccine-data
          downloaded_filename: ./data/moh/covid-19-vaccine-data/covid-19-vaccine-data.html
          postprocess: ./postprocess/moh.ts
      
      
      
      
      
      
      # No longer need to scrape the MoH pages! <3
      # - name: Fetch MOH current cases data page
      #   uses: githubocto/flat@v3
      #   with:
      #     http_url: https://www.health.govt.nz/covid-19-novel-coronavirus/covid-19-data-and-statistics/covid-19-current-cases
      #     downloaded_filename: ./data/moh/covid-19-current-cases/covid-19-current-cases.html
      #     postprocess: ./postprocess/moh.ts
      # - name: Fetch MOH case demographics data page
      #   uses: githubocto/flat@v3
      #   with:
      #     http_url: https://www.health.govt.nz/covid-19-novel-coronavirus/covid-19-data-and-statistics/covid-19-case-demographics
      #     downloaded_filename: ./data/moh/covid-19-case-demographics/covid-19-case-demographics.html
      #     postprocess: ./postprocess/moh.ts
      # - name: Fetch MOH source of cases data page
      #   uses: githubocto/flat@v3
      #   with:
      #     http_url: https://www.health.govt.nz/covid-19-novel-coronavirus/covid-19-data-and-statistics/covid-19-source-cases
      #     downloaded_filename: ./data/moh/covid-19-source-cases/covid-19-source-cases.html
      #     postprocess: ./postprocess/moh.ts
      # - name: Fetch MOH testing data page
      #   uses: githubocto/flat@v3
      #   with:
      #     http_url: https://www.health.govt.nz/covid-19-novel-coronavirus/covid-19-data-and-statistics/testing-covid-19
      #     downloaded_filename: ./data/moh/testing-covid-19/testing-covid-19.html
      #     postprocess: ./postprocess/moh.ts
      # - name: Fetch MOH vaccine data
      #   uses: githubocto/flat@v3
      #   with:
      #     http_url: https://raw.githubusercontent.com/minhealthnz/nz-covid-data/main/vaccine-data/latest/doses_by_date.csv
      #     downloaded_filename: ./data/moh/doses_by_date.csv
      