name: Get OWID data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/owid.yml
      - ./postprocess/owid.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch OWID data
        uses: githubocto/flat@v3
        with:
          http_url: https://covid.ourworldindata.org/data/owid-covid-data.csv
          downloaded_filename: ./data/owid/owid-covid-data.csv
          postprocess: ./postprocess/owid.ts
